// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = 'https://pnnapdxefbmafisglnfz.supabase.co';
const SUPABASE_PUBLISHABLE_KEY =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBubmFwZHhlZmJtYWZpc2dsbmZ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MTMzMDEsImV4cCI6MjA2OTk4OTMwMX0.67StXTkZ7-KMOalbF01tlaebcYDRNmXrJcc9n4Xwluo';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  }
);
